title: Portofolio
description: A Jekyll Landing Page Theme
sitename: Your Website
baseurl: '/portofolio'
sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - features
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME
